const UPPER_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const LOWER_CHARS = 'abcdefghijklmnopqrstuvwxyz';
const NUMBERS = '0123456789';
const SPECIAL_CHARACTERS = '!@#$%^&*()_+-=[]{}|;:,.<>?';

export const PASSWORD_CONSTANTS = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 16,
  UPPER_CHARS,
  LOWER_CHARS,
  NUMBERS,
  SPECIAL_CHARACTERS,
  ALL_CHARS: UPPER_CHARS + LOWER_CHARS + NUMBERS + SPECIAL_CHARACTERS,
};
