export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BUSSINESS_MANAGER = 'BUSSINESS_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  CUSTOMER = 'CUSTOMER',
}

export enum UserStatus {
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE',
}
